ngromeconf/ngrome-website

- index.html
**Changes**
- Index.html: add tag manager script
> feat: add tag-manager script

- index.html
- src/app/components/home/features/features.component.ts
- src/app/components/home/hero/hero.component.ts
- src/app/routes/sponsors.ts
Changes:
- Add cookie banner for compliance
> Add cookie banner for compliance

- src/app/components/home/tickets.component.ts
- src/app/components/shared/button.component.ts
- src/server/routes/v1/tickets.ts
basically I want to change the order of the tickets benefits with the registration button
from this:
to this:
> feat: change registration order

- src/app/components/home/hero/hero.component.ts
- src/app/components/home/tickets.component.ts
- src/server/routes/v1/tickets.ts
- fix width for special tickets
- sold out blind tickets
> feat: soldout blind tickets

- src/app/routes/workshops/[slug].page.ts
> Workshop page: xxl screen resolution issue

- src/app/components/sponsors/silver/silver-sponsor.component.ts
- src/server/routes/v1/sponsors.ts
Angular Wroclaw
https://twitter.com/AngularWroclaw
Angular Space
https://www.angularspace.com/
> community partner A. Wroclaw and A. Space

- src/app/components/social-share/social-share.component.ts
- src/app/models/workshop.model.ts
- src/app/routes/thank-you.[reference].[name].ts
- src/app/routes/workshops/[slug].page.ts
- src/content/workshops/angular-architects-signal-ddd-mfe.md
- src/content/workshops/angular-ngrx-masterclass.md
- src/content/workshops/ng-girls-workshop-2024-06.md
Added social share buttons using the component in repo.
Did some fixes on styles on social share button and checked the changes also on thank-you page to mantain the same layout(just a margin and display change).
Preview:
Closes: #80
> Add social share component to the workshop pages

- src/server/routes/v1/sponsors.ts
Added INEO as bronze sponsor with the following logo:
> feat: added Ineo as bronze sponsor

- src/app/components/sponsors/content/content.component.ts
- src/server/routes/v1/sponsors.ts
and fix center button sponsorship
> Lascaux as bronze sponsor

- src/app/components/sponsors/sponsor.component.ts
- src/server/routes/v1/sponsors.ts
add Cloudinary in gold sponsor
and fix padding responsive
closes #137
> Cloudinary in gold sponsor

- src/app/components/about/team/team.model.ts
> Fix Img Team in about

- src/app/components/speakers/speaker-modal.component.ts
- src/content/speakers/alex-okrushko.md
- src/content/speakers/brandon-roberts.md
- src/content/speakers/marko-stanimirović.md
feat: add speakers
fix: if in description  in modal detail speaker
are miss the title and description  talk
> Add Speakers Marko, Alex, Brandon

- .vscode/settings.json
- src/app/components/home/tickets-item.component.ts
- src/app/components/home/tickets.component.ts
- src/app/components/shared/button.component.ts
- src/app/models/ticket.interface.ts
- src/app/services/tito.service.ts
- src/server/routes/v1/tickets.ts
- src/server/routes/v1/tito-releases.ts
- src/styles.css
- vite.config.ts
> feat: add simplified ticket section

- src/server/routes/v1/tickets.ts
> feat: add early-bird sold out

- src/content/workshops/angular-performance-masterclass.md
retrieve info from linkedin https://www.linkedin.com/in/christopher-p-holder/
> Add Holder in Performance workshop

- src/app/components/layout/footer/footer.component.ts
> feat: add footer info

- src/app/components/home/hero/hero.component.ts
- src/app/components/workshops/workshop-detail.component.ts
- src/app/components/workshops/workshop-row.component.ts
- src/app/models/workshop.model.ts
- src/content/workshops/2024-06-26-1-angular-architects-signal-ddd-mfe.md
- src/content/workshops/2024-06-26-2-angular-mastering-ngrx-signalstore.md
> Add sold out workshops

- src/app/components/venue/content.component.ts
- src/content/agenda.md
- swap Natallia  with Julian
- add how to reach midas
> feat: small update agenda and venue

- src/app/pages/code-of-conduct.md
> fix: format list

- src/app/components/home/call-for-paper.component.ts
- src/app/components/shared/constant.ts
- src/app/pages/index.page.ts
> feat: cfp 2025 opening

- index.html
- src/app/components/home/call-for-paper.component.ts
- src/app/components/home/features/past-edition-sponsors.ts
- src/app/components/home/features/sponsorship-opportunity.component.ts
- src/app/components/home/hero/hero.component.ts
- src/app/components/home/tickets.component.ts
- src/app/components/layout/footer/constants.ts
- src/app/components/layout/header/constants.ts
- src/app/components/layout/loader.component.ts
- src/app/components/workshops/workshop-detail.component.ts
- src/app/components/workshops/workshop-row.component.ts
- src/app/models/workshop.model.ts
- src/app/pages/index.page.ts
- src/app/pages/workshops/[slug].page.ts
- src/app/pages/workshops/resolvers.ts
- src/app/services/loader.service.ts
- src/app/services/tito.service.ts
- src/content/index.md
- src/content/workshops/2025-06-19-1-angular-architects.md
- vite.config.ts
+ new home page
+ setup date for workshop and conference day
> feat: new workshop & home details

- src/app/components/about/team/team.model.ts
- src/app/components/agenda/content/content.component.ts
- src/app/components/venue/content.component.ts
- src/content/workshops/2025-06-19-1-angular-architects.md
Add @DavidePassafaro and Giorgio Galassi
Some details updated in the venue page
Update sticky bottom agenda component and workshop
> New team member 2025

- src/server/routes/v1/sponsors.ts
add community partner: 
angular, 
house of angular 
developer nation
> feat: add angular, house of angular and developer nation

- src/app/components/about/main-content/content.component.ts
- src/app/pages/about.page.ts
> feat: update about page content and image for NGRome conference

- src/server/routes/v1/sponsors.ts
> feat: add Nosotros Group as an event sponsor
